START umv   /home/ged_lab/__X__/Pimenov/Calc/Hydrozones/Al_Ga_In_T3H-PLP/T3H-PLP/T3H-PLP_S1_RELAX_B3LYP_cc-pVTZ_PCM_C1.log &
START umv   /home/ged_lab/__X__/Pogonin/OBJECTS/Kiselev/PBE0_cc-pVTZ_GD3/Kiselev_2_C2_cubic.log &
START umv   /home/ged_lab/__X__/Pimenov/Calc/Hydrozones/NewHydrozones/PCM/AUGMENTED/Hydrozone_C1_B3LYP_DMSO_Model5_aug-cc-pVTZ.log &
START umv   /home/ged_lab/__X__/Pogonin/OBJECTS/P_NEW/Halogen_F/B3LYP_pVTZ/ultra_f_B3LYP_pVTZ_C2v_g09_cubic.log &
START umv   /home/ged_lab/__X__/Zhabanov/students/20/lua/phth_in/el_spectra/incl_macrocycle_camB3LYP_def2tzvpd_tddft.log &
START umv   /home/ged_lab/__X__/Pimenov/Calc/Hydrozones/NewHydrozones/PCM/AUGMENTED/Hydrozone_C1_B3LYP_DMSO_Model5_aug-cc-pVTZ.log &
START umv   /home/ged_lab/__X__/TNV/OBJECTS/CN-Ph-O-Ph-OCH3/ZnN8O8C60H40/2/znpc_2_3.log &
START umv   /home/ged_lab/__X__/TNV/OBJECTS/CN-Ph-O-Ph-OCH3/ZnN8O8C60H40/2/znpc_2_3.log &
START umv   /home/ged_lab/__X__/TNV/OBJECTS/CN-Ph-O-Ph-OCH3/ZnN8O8C60H40/2/znpc_2_3.log &
START umv   /home/ged_lab/__X__/Kurochkin/OBjects/1,2-diphenoxiethane/calc2023/cubic/118.log &
START umv   /home/ged_lab/__X__/Kurochkin/OBjects/1,2-diphenoxiethane/calc2023/cubic/60.log &
START umv   /home/ged_lab/__X__/Kurochkin/OBjects/1,2-diphenoxiethane/calc2023/cubic/118.log &
START umv   /home/ged_lab/__X__/Kurochkin/OBjects/1,2-diphenoxiethane/calc2023/cubic/60.log &
START umv   /home/ged_lab/__X__/Eroshin/Objects/silatranes/Cl-silatrane/qc/MP2/c3_mp2_augccpvtz_cub.log &
START umv   /home/ged_lab/__X__/Eroshin/Objects/silatranes/Cl-silatrane/md/pyramd2/mol_xtb.xyz &
START umv   /home/ged_lab/__X__/Eroshin/Objects/silatranes/Cl-silatrane/md/pyramd1/mol_xtb.xyz &
START umv   /home/ged_lab/__X__/Eroshin/Objects/silatranes/Cl-silatrane/md/pyramd3/mol_xtb.xyz &
START umv   /home/ged_lab/__X__/Eroshin/Objects/silatranes/Me-silatrane/QST2/Me_cub.log &
